bool MixStart
uint8 MixFor
uint8 DoseSpeedB1
uint8 DoseSpeedB0
uint8 DoseFor
bool DoseStart
bool MixPosDown
bool MixPos2
bool MixPos1
bool MixPosUp
bool MixPos3
bool MixPos4
bool MixPos5
bool MixPos6
bool MixVertStart
bool MixVertStop
bool MixVertRef
bool MixVertRelRobot
---
string status
